language: node_js
sudo: required  # See http://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
group: deprecated # https://github.com/travis-ci/travis-ci/issues/6928
